version: "3"

services:

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=petdata
      - MYSQL_USER=pet-user
      - MYSQL_PASSWORD=123

  meterialrequestmysql:
    build: .
    container_name: meterialrequestmysql
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    links:
      - mysql:mysql
